spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: franciscocontatopro@gmail.com
    password: ftgvtvdbbizkgpqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
